name: CI
on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ghost
        run: bash install.sh
      - name: Run ghost
        run: ghost
  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ghost
        run: bash install.sh
      - name: Run ghost
        run: ghost
