name: CI
on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download adb
        run: sudo apt-get install adb
      - name: Run ghost
        run: python3 ghost
  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download adb
        run: brew install android-platform-tools
      - name: Run ghost
        run: python3 ghost
